# Mean-Variance-Standard Deviation Calculator
### AUX CALCs to output:
{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],   
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],   
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],   
  'max': [[6, 7, 8], [2, 5, 8], 8],   
  'min': [[0, 1, 2], [0, 3, 6], 0],   
  'sum': [[9, 12, 15], [3, 12, 21], 36]   
}

In [9]:
# {
#   'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
#   'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
#   'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
#   'max': [[6, 7, 8], [2, 5, 8], 8],
#   'min': [[0, 1, 2], [0, 3, 6], 0],
#   'sum': [[9, 12, 15], [3, 12, 21], 36]
# }

In [10]:
import numpy as np
np.__version__

'1.23.5'

In [11]:
lst = [0,1,2,3,4,5,6,7,8]
a = np.reshape(lst, (3,3))
a, a.dtype

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 dtype('int32'))

In [24]:
# 'mean': [axis1, axis2, flattened],
print(a.mean(axis=0))
print(a.mean(axis=1))
a.mean(), type(a.mean()), a.mean(axis=None), a.mean(axis=(0,1)), type(None)

[3. 4. 5.]
[1. 4. 7.]


(4.0, numpy.float64, 4.0, 4.0, NoneType)

In [21]:
# convert to plian Py list
am0_l = list(a.mean(axis=0))
am0_l, type(am0_l), type(am0_l[1])

([3.0, 4.0, 5.0], list, numpy.float64)

In [13]:
# 'variance': [axis1, axis2, flattened],
print(a.var(axis=0))
print(a.var(axis=1))
a.var(), type(a.var())

[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


(6.666666666666667, numpy.float64)

In [14]:
#  'standard deviation': [axis1, axis2, flattened],
print(a.std(axis=0))
print(a.std(axis=1))
a.std(), type(a.std())

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


(2.581988897471611, numpy.float64)

In [18]:
# just to see float prescision
am0 = a.mean(axis=0)
print(am0, type(am0), am0.dtype)
as1 = a.std(axis=1)
as1, type(as1), as1.dtype

[3. 4. 5.] <class 'numpy.ndarray'> float64


(array([0.81649658, 0.81649658, 0.81649658]), numpy.ndarray, dtype('float64'))