# Cramer's rule
In linear algebra, Cramer's rule is an explicit formula for the solution of a system of linear equations with as many equations as unknowns, valid whenever the system has a unique solution. It expresses the solution in terms of the determinants of the (square) coefficient matrix and of matrices obtained from it by replacing one column by the column vector of right-sides of the equations. It is named after Gabriel Cramer (1704–1752), who published the rule for an arbitrary number of unknowns in 1750,[1][2] although Colin Maclaurin also published special cases of the rule in 1748[3] (and possibly knew of it as early as 1729).[4][5][6]

In [39]:
import numpy as np
np.__version__

'1.23.5'

In [40]:
C = np.array([[3, 1],
              [2, 5]])
C

array([[3, 1],
       [2, 5]])

In [41]:
v = np.linspace(2, 3, num=2, dtype=int)
v

array([2, 3])

In [42]:
m = C * v
m

array([[ 6,  3],
       [ 4, 15]])

In [43]:
i = np.array(['x', 'y'])
i

array(['x', 'y'], dtype='<U1')

### Pratical case of a system of two linear ecuations
3x + 1y = 9   
2x + 3y = 13

In [44]:
## Matrix format:
#   C    u     r
# [3 1] [x]   [ 9]   
# [2 3] [y] = [13]

In [45]:
C = C = np.array([[3, 1],
              [2, 3]])
C, C[0][1], C[0, 1]

(array([[3, 1],
        [2, 3]]),
 1,
 1)

In [46]:
r = np.array([9, 13])
r

array([ 9, 13])

In [47]:
Mx = np.array([[r[0], C[0, 1]],
                [r[1], C[1, 1]]])
Mx

array([[ 9,  1],
       [13,  3]])

In [48]:
My = np.array([[C[0, 0], r[0]],
                [C[1, 0], r[1]]])
My

array([[ 3,  9],
       [ 2, 13]])

In [49]:
x = round(np.linalg.det(Mx) / np.linalg.det(C), 2)
x 

2.0

In [50]:
y = round(np.linalg.det(My) / np.linalg.det(C), 2)
y

3.0

In [51]:
u = np.array([x, y])
u

array([2., 3.])

In [52]:
mult = C.dot(u)
mult

array([ 9., 13.])