# Numpy Introduccion A
- https://es.wikipedia.org/wiki/NumPy
- https://numpy.org/doc/stable/reference/index.html
- https://www.projectpro.io/article/numpy-projects/641 (numpy-user.pdf)
- https://python-course.eu/numerical-programming/creating-numpy-arrays.php
- https://www.w3resource.com/python-exercises/numpy/index.php
- https://favtutor.com/blogs/numpy-exercises-python

In [5]:
# import sys        # usualy imported in numpy projects ¿?
import numpy as np
np.__version__

'1.23.5'

### Basic numpy numbers

In [6]:
a = np.int8(5)
b = np.int8(3)
print(a + b, type(a + b))

8 <class 'numpy.int8'>


In [7]:
a = np.int8(126)
print(a, type(a))

126 <class 'numpy.int8'>


In [8]:
b = a * a
print(b, type(b))

4 <class 'numpy.int8'>


C:\Users\jm\AppData\Local\Temp\ipykernel_4944\3653347308.py:1: RuntimeWarning: overflow encountered in byte_scalars
  b = a * a


In [9]:
c = np.int64
c = a * a
print(c, type(c))

4 <class 'numpy.int8'>


C:\Users\jm\AppData\Local\Temp\ipykernel_4944\1239678630.py:2: RuntimeWarning: overflow encountered in byte_scalars
  c = a * a


In [10]:
d = np.int8(252)
print(d, type(d))

-4 <class 'numpy.int8'>


In [11]:
e = np.int64(252)
print(e, type(e))

252 <class 'numpy.int64'>


In [12]:
f = e * e
print(f, type(f))

63504 <class 'numpy.int64'>


### Numpy 1D array creation functions

In [13]:
np.arange(34)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [14]:
for i in np.arange(7):
    print(i, type(i), end='  ')

0 <class 'numpy.int32'>  1 <class 'numpy.int32'>  2 <class 'numpy.int32'>  3 <class 'numpy.int32'>  4 <class 'numpy.int32'>  5 <class 'numpy.int32'>  6 <class 'numpy.int32'>  

### Recursive Fibonacci contrucción with np numbers.
- With 16 bits = 2 ** 16 = 65536 (from 0 to 65535)

In [15]:
2 ** 16

65536

In [16]:
def rfibo(n):
    try:
        assert n >= 0 and (type(n) == int or type(n) == np.int32)
        if n == 0: return 0
        elif n == 1: return 1
        elif n > 1: return rfibo(n-2) + rfibo(n-1)
    except (TypeError, AssertionError):
        return 'ERROR: "n" must be an integer grater than 0'

In [17]:
for i in range(34):
    #print('rfibo_py(',i,'): ', rfibo_py(i), sep='', end='  ')
    print(rfibo(i), end=' ')

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 

In [18]:
for i in range(34):
    #print('rfibo_py(',i,'): ', rfibo_py(i), sep='', end='  ')
    i = np.int32(i)
    print(rfibo(i), end=' ')

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 

In [19]:
i = np.int32(0)
while i < 35:
    print(rfibo_np(i), end=' ')
    i += 1

NameError: name 'rfibo_np' is not defined

In [ ]:
for i in np.arange(34):
    #print('rfibo_py(',i,'): ', rfibo_py(i), sep='', end='  ')
    print(rfibo(i), end=' ')

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 

In [ ]:
i = 0
while i < 35:
    print(rfibo_py(i), end=' ')
    i += 1

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 

In [ ]:
# Python 3: Fibonacci series up to n
def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a + b
    print()
fib(1e20)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 20365011074 32951280099 53316291173 86267571272 139583862445 225851433717 365435296162 591286729879 956722026041 1548008755920 2504730781961 4052739537881 6557470319842 10610209857723 17167680177565 27777890035288 44945570212853 72723460248141 117669030460994 190392490709135 308061521170129 498454011879264 806515533049393 1304969544928657 2111485077978050 3416454622906707 5527939700884757 8944394323791464 14472334024676221 23416728348467685 37889062373143906 61305790721611591 99194853094755497 160500643816367088 259695496911122585 420196140727489673 679891637638612258 1100087778366101931 1779979416004714189 2880067194370816120 4660046610375530309 754011380474634642

### Basic Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([0, 1, 2, 3])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2, 2.5, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [ ]:
a[0], a[1]

(0, 1)

In [ ]:
a[[0,1]]

array([0, 1])

In [ ]:
b[[1, 2, -2]]

array([0.5, 1. , 2.5])

In [ ]:
a[::-1]

array([3, 2, 1, 0])

### Array Types

In [ ]:
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

In [ ]:
#...

### Dimendions & Shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

### Custom Sequence Generation - List Comprehension

In [ ]:
table_of_9 = [x for x in range(0, 100, 9)]
print(table_of_9)

[0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]


In [22]:
table_of_9 = np.arange(0, 100, 9)
print(table_of_9)

[ 0  9 18 27 36 45 54 63 72 81 90 99]


### Matrix Multiplication


In [23]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]


In [25]:
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

Result of the said matrix multiplication:
[[1 2]
 [3 4]]


In [30]:
pn = np.array(p)
qn = np.array(q)
print('original numpy matrix:')
print(pn)
print(qn)

original numpy matrix:
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]


In [34]:
result2 = np.matmul(p, q)
print(result2)

[[1 2]
 [3 4]]


In [35]:
pn = np.array(p)
qn = np.array(q)
print('original numpy matrix:')
print(pn)
print(qn)

original numpy matrix:
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]


In [36]:
result3 = pn@qn
print(result3)

[[1 2]
 [3 4]]


In [37]:
result4 = np.dot(pn, qn)
print(result4)

[[1 2]
 [3 4]]
