# Numpy Operations -

In [273]:
import sys              # we are going to use sys now
import numpy as np
np.__version__

'1.23.5'

### Broadcasting and Vectorized Operations

In [274]:
a = np.arange(5)
a, type(a)

(array([0, 1, 2, 3, 4]), numpy.ndarray)

In [275]:
print(a, type(a), sep='  -  ')

[0 1 2 3 4]  -  <class 'numpy.ndarray'>


In [276]:
a * 10

array([ 0, 10, 20, 30, 40])

In [277]:
a + 10

array([10, 11, 12, 13, 14])

In [278]:
a

array([0, 1, 2, 3, 4])

> array 'a' don't change. Numpy is an inmutable first library. The op. return a new array, unless...

In [279]:
a += 10
a

array([10, 11, 12, 13, 14])

##### In Plain Python:

In [280]:
la = [i for i in range(5)]  # list comprehension
la, type(la)

([0, 1, 2, 3, 4], list)

In [281]:
lb = [el * 10 for el in la] # l. c. again
lb, type(lb), la

([0, 10, 20, 30, 40], list, [0, 1, 2, 3, 4])

In [282]:
lc = list(map(lambda x: x * 10, la))
lc, type(lc), la

([0, 10, 20, 30, 40], list, [0, 1, 2, 3, 4])

In [283]:
# for i in range(len(la)):
#     la[i] = la[i] * 10
# la

> No only between array and scalar but also between arrays

In [284]:
c = np.array([10 for i in range(4)])
d = np.linspace(10, 10, num=4, dtype=int)
c, d

(array([10, 10, 10, 10]), array([10, 10, 10, 10]))

In [285]:
c + d

array([20, 20, 20, 20])

In [286]:
a = np.arange(4)
b = np.array([10, 10, 10, 10])
a, b

(array([0, 1, 2, 3]), array([10, 10, 10, 10]))

In [287]:
a + b

array([10, 11, 12, 13])

In [288]:
a * b

array([ 0, 10, 20, 30])

In [289]:
c * d

array([100, 100, 100, 100])

* Arrays must be online and have the same shape.

### Boolean arrays
(Alse called masks)   
__very important__

In [290]:
a

array([0, 1, 2, 3])

In [291]:
a[[0, -1]]

array([0, 3])

In [292]:
a[[True, False, False, True]]

array([0, 3])

In [293]:
a >= 2      # a Boolean array is born

array([False, False,  True,  True])

In [294]:
a[a >= 2]   # a Query method

array([2, 3])

In [295]:
a.mean()

1.5

In [296]:
a[a > a.mean()]

array([2, 3])

In [297]:
a[a < a.mean()]

array([0, 1])

In [298]:
a[~(a > a.mean())]

array([0, 1])

In [299]:
a[(a == 0) | (a == 1)]      # or

array([0, 1])

In [300]:
a[(a <= 2) & (a % 2 == 1)]  # and

array([1])

In [301]:
A = np.random.randint(100, size=(3, 3))
A

array([[96, 93, 19],
       [44, 93, 89],
       [25, 83, 63]])

In [302]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([96, 19, 93, 25, 63])

In [303]:
B = A > 30
B

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [304]:
A.shape, A.ndim, A.size, B.shape, B.ndim, B.size

((3, 3), 2, 9, (3, 3), 2, 9)

In [305]:
c = A[A > 30]
c, c.shape, c.ndim, c.size

(array([96, 93, 44, 93, 89, 83, 63]), (7,), 1, 7)

### Linear Algebra
Linear algebra provides a way of compactly representing and operating on sets of linear
equations
-  By A ∈ R _m×n we denote a matrix with m rows and n columns, where the entries of A
are real numbers.
-  By x ∈ Rn, we denote a vector with n entries. By convention, an n-dimensional vector
is often thought of as a matrix with n rows and 1 column, known as a column vector.
> http://cs229.stanford.edu/summer2020/cs229-linalg.pdf

In [311]:
M1 = np.random.randint(9, size=(3, 2))
M1

array([[1, 8],
       [2, 6],
       [2, 4]])

In [314]:
M1.transpose()

array([[1, 2, 2],
       [8, 6, 4]])

In [316]:
M1

array([[1, 8],
       [2, 6],
       [2, 4]])

In [317]:
c, c.transpose()

(array([96, 93, 44, 93, 89, 83, 63]), array([96, 93, 44, 93, 89, 83, 63]))

##### Matrix Multiplication
- dot product, inner product.

In [319]:
a, a.transpose()

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [321]:
a.dot(a.transpose())

14

- outer product.

In [322]:
np.outer(a, a.transpose())

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])