#  NumPy course created by Keith Galli.
### NumPy faster than plain Python Lists - Performance Benefict
- Faster to read less bytes of memory
    - NumPy elements aren't objects (dtype int8, 16, 32; float64, <U1, <U32)
- No tye checking when iterating trought elements
    - all elements the same 'dtype'
- NumPu utilizes continous memory (plain Python nop - kind of scatterd around)
    - SIMD vector procesing unit usage (Single Instruction Multiple Data).
    - Efective cache utilization.
### NumPy different to list - Usefuless Benefits
- Can do the same as with lists: insertion, deletion, appending, concatenetion, etc.
- Can do more: e.g multpy arrays, arrays and int, etc. we'll se later
### Applicatoins of Numpy
- MATLAB replacement: tons of math - other scipy.org.
- Plotting (Matplotlib)
- Backend or other very useful libraries (Pandas, Connect 4, Digital Photography).
- Machine Learning: pretty important for. (idea of tensors)


What is NumPy

Why are Numpy arrays faster than regular Python lists?


Numpy does not perform type checking while iterating through objects.


Numpy uses fixed types.


Numpy uses contiguous memory.


**All of the above.**

### Star with the code
pip install numpy - import numpy as np

In [2]:
import numpy as np
a8 = np.array([1,2,3], dtype= np.int8)
a32 = np.array([1,2,3], dtype= 'int32')
print(a8.itemsize, a32.itemsize, a8.nbytes, a32.nbytes)

1 4 3 12


In [7]:
ab = np.array([[1,2,3,4], [50, 60, 70, 80]])
ab

array([[ 1,  2,  3,  4],
       [50, 60, 70, 80]])

In [12]:
ac = np.array([a8, a32])
print(ac, ac.dtype)

[[1 2 3]
 [1 2 3]] int32


In [13]:
ab[0, :]

array([1, 2, 3, 4])

In [14]:
ab[1]

array([50, 60, 70, 80])

In [15]:
ab[:, 2]

array([ 3, 70])

In [16]:
ab[,2]

SyntaxError: invalid syntax (3983064963.py, line 1)