#  NumPy course created by Keith Galli.
### NumPy faster than plain Python Lists - Performance Benefict
- Faster to read less bytes of memory
    - NumPy elements aren't objects (dtype int8, 16, 32; float64, <U1, <U32)
- No tye checking when iterating trought elements
    - all elements the same 'dtype'
- NumPu utilizes continous memory (plain Python nop - kind of scatterd around)
    - SIMD vector procesing unit usage (Single Instruction Multiple Data).
    - Efective cache utilization.
### NumPy different to list - Usefuless Benefits
- Can do the same as with lists: insertion, deletion, appending, concatenetion, etc.
- Can do more: e.g multpy arrays, arrays and int, etc. we'll se later
### Applicatoins of Numpy
- MATLAB replacement: tons of math - other scipy.org.
- Plotting (Matplotlib)
- Backend or other very useful libraries (Pandas, Connect 4, Digital Photography).
- Machine Learning: pretty important for. (idea of tensors)


What is NumPy

Why are Numpy arrays faster than regular Python lists?


Numpy does not perform type checking while iterating through objects.


Numpy uses fixed types.


Numpy uses contiguous memory.


**All of the above.**

### Star with the code
pip install numpy - import numpy as np

In [27]:
import numpy as np
a8 = np.array([1,2,3], dtype= np.int8)
a32 = np.array([1,2,3], dtype= 'int32')
print(a8.itemsize, a32.itemsize, a8.nbytes, a32.nbytes)

1 4 3 12


In [28]:
ab = np.array([[1,2,3,4], [50, 60, 70, 80]])
ab

array([[ 1,  2,  3,  4],
       [50, 60, 70, 80]])

In [29]:
ac = np.array([a8, a32])
print(ac, ac.dtype)

[[1 2 3]
 [1 2 3]] int32


In [30]:
ab[0, :]

array([1, 2, 3, 4])

In [31]:
ab[1]

array([50, 60, 70, 80])

In [32]:
ab[:, 2]

array([ 3, 70])

In [33]:
ab[,2]

SyntaxError: invalid syntax (3983064963.py, line 1)

## Mathematics
Element wise operations: +,-,*,** a number (ej. sum num to every element).    
The same for funcs like trigonometrics (an all defined i imagine) 
Also sum to arrays (but i doubt is this is linear algebra yet)

In [ ]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [ ]:
b + 2, b -2, b * 2, b ** 3

(array([2, 3, 4, 5, 6]),
 array([-2, -1,  0,  1,  2]),
 array([0, 2, 4, 6, 8]),
 array([ 0,  1,  8, 27, 64], dtype=int32))

In [ ]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
a + b, np.tanh(a)

(array([1., 2., 3., 4., 5.]),
 array([0.76159416, 0.76159416, 0.76159416, 0.76159416, 0.76159416]))

### Linear Algebra

In [38]:
x = np.ones((2,3))
print(x)

y = np.full((3,2), 2)
print(b)

x @ y, np.matmul(x, y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


(array([[6., 6.],
        [6., 6.]]),
 array([[6., 6.],
        [6., 6.]]))

### Statistics

In [44]:
stats = np.array([[1,3,5],[2,4,6]])
stats

array([[1, 3, 5],
       [2, 4, 6]])

In [45]:
np.min(stats), np.min(stats, axis=0), np.min(stats, axis=1)

(1, array([1, 3, 5]), array([1, 2]))

In [46]:
s1 = np.array([[1,3,5],[9,8,7],[2,4,6]])
s1

array([[1, 3, 5],
       [9, 8, 7],
       [2, 4, 6]])

In [48]:
np.min(s1), np.min(s1, axis=0), np.min(s1, axis=1)

(1, array([1, 3, 5]), array([1, 7, 2]))

In [49]:
np.max(s1, axis=1).sum()

20

## Reorganizing arrays
- reshape, vstack, hstack

## Loading Data and Advance Indexing
- Loading data without the use of any other module
- Boolean array, filtering & Advance Indexing

In [50]:
fd = np.genfromtxt('data.txt', delimiter=',')
fd

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 15., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [51]:
fd = fd.astype(np.int8)
fd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 15, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [52]:
print(fd)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 15 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
