#  NumPy course created by Keith Galli.
### NumPy faster than plain Python Lists - Performance Benefict
- Faster to read less bytes of memory
    - NumPy elements aren't objects (dtype int8, 16, 32; float64, <U1, <U32)
- No tye checking when iterating trought elements
    - all elements the same 'dtype'
- NumPu utilizes continous memory (plain Python nop - kind of scatterd around)
    - SIMD vector procesing unit usage (Single Instruction Multiple Data).
    - Efective cache utilization.
### NumPy different to list - Usefuless Benefits
- Can do the same as with lists: insertion, deletion, appending, concatenetion, etc.
- Can do more: e.g multpy arrays, arrays and int, etc. we'll se later
### Applicatoins of Numpy
- MATLAB replacement: tons of math - other scipy.org.
- Plotting (Matplotlib)
- Backend or other very useful libraries (Pandas, Connect 4, Digital Photography).
- Machine Learning: pretty important for. (idea of tensors)


What is NumPy

Why are Numpy arrays faster than regular Python lists?


Numpy does not perform type checking while iterating through objects.


Numpy uses fixed types.


Numpy uses contiguous memory.


**All of the above.**

### Star with the code
pip install numpy - import numpy as np

In [93]:
import numpy as np
a8 = np.array([1,2,3], dtype= np.int8)
a32 = np.array([1,2,3], dtype= 'int32')
print(a8.itemsize, a32.itemsize, a8.nbytes, a32.nbytes)

1 4 3 12


In [94]:
ab = np.array([[1,2,3,4], [50, 60, 70, 80]])
ab

array([[ 1,  2,  3,  4],
       [50, 60, 70, 80]])

In [95]:
ac = np.array([a8, a32])
print(ac, ac.dtype)

[[1 2 3]
 [1 2 3]] int32


In [96]:
ab[0, :]

array([1, 2, 3, 4])

In [97]:
ab[1]

array([50, 60, 70, 80])

In [98]:
ab[:, 2]

array([ 3, 70])

In [99]:
ab[,2]

SyntaxError: invalid syntax (3983064963.py, line 1)

## Mathematics
Element wise operations: +,-,*,** a number (ej. sum num to every element).    
The same for funcs like trigonometrics (an all defined i imagine) 
Also sum to arrays (but i doubt is this is linear algebra yet)

In [ ]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [ ]:
b + 2, b -2, b * 2, b ** 3

(array([2, 3, 4, 5, 6]),
 array([-2, -1,  0,  1,  2]),
 array([0, 2, 4, 6, 8]),
 array([ 0,  1,  8, 27, 64], dtype=int32))

In [ ]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
a + b, np.tanh(a)

(array([1., 2., 3., 4., 5.]),
 array([0.76159416, 0.76159416, 0.76159416, 0.76159416, 0.76159416]))

### Linear Algebra

In [ ]:
x = np.ones((2,3))
print(x)

y = np.full((3,2), 2)
print(b)

x @ y, np.matmul(x, y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


(array([[6., 6.],
        [6., 6.]]),
 array([[6., 6.],
        [6., 6.]]))

### Statistics

In [ ]:
stats = np.array([[1,3,5],[2,4,6]])
stats

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np.min(stats), np.min(stats, axis=0), np.min(stats, axis=1)

(1, array([1, 3, 5]), array([1, 2]))

In [ ]:
s1 = np.array([[1,3,5],[9,8,7],[2,4,6]])
s1

array([[1, 3, 5],
       [9, 8, 7],
       [2, 4, 6]])

In [ ]:
np.min(s1), np.min(s1, axis=0), np.min(s1, axis=1)

(1, array([1, 3, 5]), array([1, 7, 2]))

In [ ]:
np.max(s1, axis=1).sum()

20

## Reorganizing arrays
- reshape, vstack, hstack

## Loading Data and Advance Indexing
- Loading data without the use of any other module
- Boolean array, filtering & Advance Indexing

In [100]:
fd = np.genfromtxt('data.txt', delimiter=',')
fd

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 15., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

In [101]:
fd = fd.astype(np.int8)
fd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 15, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int8)

In [102]:
print(fd)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 15 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### Boolean Masking and Advance Indexing

In [103]:
fd < 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [104]:
fd[fd < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [105]:
# You can index with a list in numpy (thats why the below wa posible)
np_array = np.arange(1, 10)
print(np_array)

# I want the 2, the five and the nine (thr last el)
np_array[[1,4,-1]]

[1 2 3 4 5 6 7 8 9]


array([2, 5, 9])

In [106]:
# Naw y want the even numbers
print(np_array %2 == 0)
np_array[np_array %2 == 0]

[False  True False  True False  True False  True False]


array([2, 4, 6, 8])

#### AND other kind of indexind with selection (filtering)
- np.any(), np.all(), with fd array

In [107]:
fd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 15, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int8)

In [108]:
# See the columns in fd that have at least one element < 15
print(np.any(fd < 15, axis=1))
fd[np.any(fd < 15, axis=1)]

[ True  True  True False False False]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 15, 14, 15]], dtype=int8)

In [109]:
# rows w/elements grater then 15
print(np.any(fd > 15, axis=1))
fd[np.any(fd > 15, axis=1)]

[False False False  True  True  True]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int8)

In [110]:
fdt = fd.T
fd, fdt

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 15, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]], dtype=int8),
 array([[ 1,  6, 11, 16, 21, 26],
        [ 2,  7, 12, 17, 22, 27],
        [ 3,  8, 15, 18, 23, 28],
        [ 4,  9, 14, 19, 24, 29],
        [ 5, 10, 15, 20, 25, 30]], dtype=int8))

In [111]:
print(fdt[np.any(fdt > 15, axis=0)]) # filas cuyas columnas tienen al menos un el > 15
print(fdt[np.any(fdt > 15, axis=1)]) # cols cuyas filas tiene ual menos un el > 15 ¿?

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 6

In [115]:
#print(fdt[np.all(fdt > 15, axis=0)]) # filas cuyas columnas tienen todos los elems > 15
print(fdt[np.all(fdt > 15, axis=1)]) # cols cuyas filas tiene todos los elems > 15 ¿? NING
print(np.all(fdt > 15, axis=1))
print(np.all(fdt > 15))

[]
[False False False False False]
False


In [116]:
print(fd)
print((fd > 15) & (fd < 20))        # like pandas
fd[(fd > 15) & (fd < 20)]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 15 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True False]
 [False False False False False]
 [False False False False False]]


array([16, 17, 18, 19], dtype=int8)

In [117]:
print(fd)
print(~((fd > 15) & (fd < 20)))        # like pandas
fd[~((fd > 15) & (fd < 20))]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 15 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 15, 14, 15, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int8)

In [120]:
#  Quiz 1 en fd how to index only 11 12 - 16 17
print(fd[2:3, 0:1])    # NOP high limit NOT inclusive (open range)
fd[2:4, 0:2]

[[11]]


array([[11, 12],
       [16, 17]], dtype=int8)

In [123]:
# Q2 index the semi-diag 2 8 14 20
print(fd[[(0,1), (1,2), (2,3)]] )      # NOP!
fd[[0,1,2,3], [1,2,3,4]]                # Two list indexs, one for every coordenate

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 6  7  8  9 10]
  [11 12 15 14 15]]

 [[11 12 15 14 15]
  [16 17 18 19 20]]]


array([ 2,  8, 14, 20], dtype=int8)

In [127]:
# Q3 index parts of matrix fd like 4 5   24 25  29 30
print(fd[[0,4,5], 3:5])        # combination of list & slice in indexing
fd[[0,4,5], 3:]                # better cause is the last colums

[[ 4  5]
 [24 25]
 [29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int8)